import {chromium as playwright} from 'playwright';
import chromium from '@sparticuz/chromium';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import assert from 'node:assert/strict';
import {encodeText} from '../src/core.js';
const root=path.resolve('.'), report={version:JSON.parse(fs.readFileSync('package.json')).version,date:'2026-10-01',checks:[],performance:[],errors:[]};
fs.mkdirSync('docs/screenshots',{recursive:true});
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let filename=decodeURIComponent(u.pathname).replace(/^\/typebench\//,'/');if(filename.endsWith('/'))filename+='index.html';const full=path.resolve(root,'.'+filename);if(!full.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(full,(e,data)=>{if(e){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.md':'text/plain'})[path.extname(full)]||'text/plain');res.end(data);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}/typebench/`;
const browser=await playwright.launch({executablePath:process.env.CHROMIUM_EXECUTABLE || await chromium.executablePath(),args:chromium.args.filter(x=>!['--single-process','--disable-web-security','--allow-running-insecure-content','--disable-site-isolation-trials'].includes(x)),headless:true});
report.browser=browser.version();
const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true});
const p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push(e.message));p.on('dialog',d=>d.accept());
const check=(name)=>{report.checks.push(name);console.log('PASS',name);};
const waitSaved=page=>page.waitForFunction(()=>document.getElementById('browserStatus').textContent.includes('Saved in this browser'));
const editor=page=>page.locator('.cm-content');
async function readDownload(page,action){const promise=page.waitForEvent('download');await action();const d=await promise;return {name:d.suggestedFilename(),bytes:fs.readFileSync(await d.path())};}
async function download(page){return readDownload(page,()=>page.locator('#download').click());}
async function open(page,name,buffer){await page.locator('#filePicker').setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.from(buffer)});await page.waitForFunction(name=>document.getElementById('filePath').textContent===name,name);}
try{
  await p.goto(url);await waitSaved(p);await p.locator('#emptyNew').waitFor();check('Cold start is empty, with New and Open actions');
  await p.screenshot({path:'docs/screenshots/empty-dark.png'});
  await p.locator('#emptyNew').click();await editor(p).fill('A workshop note.\nUnicode: café, 日本語, 🛠️\n');await waitSaved(p);
  const d=await download(p);assert.equal(d.bytes.toString(),'A workshop note.\nUnicode: café, 日本語, 🛠️\n');check('New, edit, Unicode, native download');
  await p.keyboard.press('F2');await p.locator('#nameInput').fill('notes/workshop.txt');await p.locator('#nameForm [type=submit]').click();await p.waitForFunction(()=>document.getElementById('filePath').textContent==='notes/workshop.txt');
  await p.locator('#actionsOpen').click();await p.locator('#duplicate').click();assert.equal(await p.locator('#filePath').textContent(),'notes/workshop (2).txt');check('Rename relative path and duplicate without overwriting');
  await p.locator('#new').click();await editor(p).fill('second tab');await p.waitForTimeout(650);await editor(p).press('End');await p.keyboard.type(' change');await p.locator('#undo').click();assert.equal(await editor(p).innerText(),'second tab');await p.locator('#redo').click();assert.equal(await editor(p).innerText(),'second tab change');
  await p.getByRole('tab',{name:'notes/workshop.txt',exact:false}).click();assert((await editor(p).innerText()).includes('Unicode'));await p.getByRole('tab',{name:'untitled.txt',exact:false}).click();await p.locator('#undo').click();assert.equal(await editor(p).innerText(),'second tab');check('Independent undo/redo across tab switches');
  await p.locator('#actionsOpen').click();await p.locator('#closeDoc').click();await p.locator('#recover').click();await p.getByRole('button',{name:'Restore untitled.txt',exact:true}).click();assert.equal(await editor(p).innerText(),'second tab');await p.locator('#redo').click();assert.equal(await editor(p).innerText(),'second tab change');check('Close and reopen preserves in-session history');
  const mixed=Buffer.from('\ufeffone\r\ntwo\nthree\rfour  \r\n');await open(p,'mixed.txt',mixed);assert.equal(await p.locator('#eol').textContent(),'Mixed EOL');assert.deepEqual((await download(p)).bytes,mixed);check('Mixed LF/CRLF/CR and UTF-8 BOM byte-for-byte round trip');
  for(const encoding of ['utf-16le','utf-16be']){const bytes=encodeText('café 🛠️\r\n日本語\n',encoding,true);await open(p,encoding+'.txt',bytes);assert.deepEqual((await download(p)).bytes,Buffer.from(bytes));}check('UTF-16LE/BE BOM byte-for-byte round trips');
  await open(p,'blink.ino',Buffer.from('// Blink a light\nvoid setup() {\n  pinMode(LED_BUILTIN, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(LED_BUILTIN, HIGH);\n  delay(500);\n  digitalWrite(LED_BUILTIN, LOW);\n  delay(500);\n}\n'));
  assert.equal(await p.locator('#language').inputValue(),'arduino');assert(await p.locator('.cm-line span').count()>0);
  const before=(await download(p)).bytes;await p.locator('#language').selectOption('text');assert.deepEqual((await download(p)).bytes,before);check('Arduino base highlighting and language switch preserves bytes');
  await open(p,'orbit.pde',Buffer.from('// An orbit in the workshop\nPVector center;\n\nvoid setup() {\n  size(640, 480);\n  center = new PVector(width/2, height/2);\n}\n\nvoid draw() {\n  background(24);\n  fill(195, 235, 136);\n  ellipse(center.x, center.y, 80, 80);\n}\n'));
  assert.equal(await p.locator('#language').inputValue(),'processing');assert(await p.locator('.cm-line span').count()>0);check('Processing base highlighting with realistic sketch');
  await p.screenshot({path:'docs/screenshots/editor-dark.png'});
  await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption('light');await p.locator('#wrap').check();await p.locator('#fontSize').selectOption('18');await p.locator('#settingsDialog [data-close]').click();await p.screenshot({path:'docs/screenshots/editor-light.png'});
  await waitSaved(p);await p.reload();await waitSaved(p);assert.equal(await p.locator('#language').inputValue(),'processing');assert.equal(await p.locator('html').getAttribute('data-theme'),'light');assert((await editor(p).innerText()).includes('PVector'));check('Refresh restores text, active tab, language and settings');
  await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption('contrast');await p.locator('#settingsDialog [data-close]').click();await p.screenshot({path:'docs/screenshots/editor-contrast.png'});check('Dark, light, high-contrast rendering');
  const exported=await readDownload(p,()=>p.locator('#backup').click());const workspace=JSON.parse(exported.bytes);assert(workspace.documents.length>=6);await p.locator('#new').click();await editor(p).fill('temporary');await p.locator('#workspacePicker').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:exported.bytes});await p.locator('#confirmYes').click();await p.waitForFunction(count=>document.querySelectorAll('[role=tab]').length===count,workspace.documents.length);const exported2=await readDownload(p,()=>p.locator('#backup').click());assert.deepEqual(JSON.parse(exported2.bytes).documents.map(x=>[x.name,x.raw,x.language]),workspace.documents.map(x=>[x.name,x.raw,x.language]));check('Workspace export/import round trip');
  await waitSaved(p);const p2=await context.newPage();p2.on('dialog',d=>d.accept());await p2.goto(url);await waitSaved(p2);await editor(p).fill('first window revision');await waitSaved(p);await editor(p2).fill('second window preserved');await p2.waitForFunction(()=>document.getElementById('bannerText').textContent.includes('another window'));const recovery=await readDownload(p2,()=>p2.locator('#emergencyExport').click());assert(JSON.parse(recovery.bytes).documents.some(d=>d.raw==='second window preserved'));await p2.close();check('Two-window conflict prevents silent overwrite and exports losing copy');
  await p.evaluate(()=>{window.__xss=0;});await open(p,'untrusted.html',Buffer.from('<script>window.__xss=1</script><img src="https://example.invalid/pixel">'));assert.equal(await p.evaluate(()=>window.__xss),0);assert.equal(await p.locator('img[src*="example.invalid"]').count(),0);check('Imported HTML remains source text');
  const dt=await p.evaluateHandle(()=>{const data=new DataTransfer();data.items.add(new File(['Dropped café\r\n'], 'dropped.txt',{type:'text/plain'}));return data;});await p.dispatchEvent('body','drop',{dataTransfer:dt});await p.waitForFunction(()=>document.getElementById('filePath').textContent==='dropped.txt');assert.equal((await download(p)).bytes.toString(),'Dropped café\r\n');check('Drag/drop file import');
  await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();await p.locator('.cm-content').waitFor();await p.locator('#new').click();await editor(p).fill('offline text');assert.equal((await download(p)).bytes.toString(),'offline text');await context.setOffline(false);check('Offline reload, editing and export under subdirectory');
  await p.setViewportSize({width:390,height:844});await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption('dark');await p.locator('#settingsDialog [data-close]').click();if(await p.locator('#sidebarToggle').getAttribute('aria-expanded')==='true')await p.locator('#sidebarToggle').click();await p.screenshot({path:'docs/screenshots/mobile.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await editor(p).fill('mobile edit');assert.equal((await download(p)).bytes.toString(),'mobile edit');check('390 px mobile layout and basic editing');
  await p.setViewportSize({width:1440,height:960});await editor(p).focus();await p.keyboard.press('Escape');await p.keyboard.press('Tab');assert(!(await p.evaluate(()=>document.activeElement.classList.contains('cm-content'))));check('Keyboard escape from editor focus');
  const cFail=await browser.newContext();await cFail.addInitScript(()=>{const orig=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...rest){if(mode==='readwrite')throw new DOMException('Simulated quota exceeded','QuotaExceededError');return orig.call(this,names,mode,...rest);};});const fail=await cFail.newPage();fail.on('dialog',d=>d.accept());await fail.goto(url);await fail.locator('#emptyNew').click();await editor(fail).fill('keep this work');await fail.waitForFunction(()=>document.getElementById('bannerText').textContent.includes('could not save'));assert.equal((await download(fail)).bytes.toString(),'keep this work');const failJson=await readDownload(fail,()=>fail.locator('#emergencyExport').click());assert(JSON.parse(failJson.bytes).documents.some(d=>d.raw==='keep this work'));await cFail.close();check('Quota failure retains text and provides recovery export');
  const perfContext=await browser.newContext();const perf=await perfContext.newPage();perf.setDefaultTimeout(120000);perf.on('dialog',d=>d.accept());await perf.goto(url);
  for(const size of [100*1024,1024*1024,5*1024*1024,10*1024*1024]){const bytes=Buffer.from(('A plain text line for the workbench.\n').repeat(Math.ceil(size/36)).slice(0,size));const start=Date.now();await open(perf,'size-'+size+'.txt',bytes);const opened=Date.now()-start;const out=await download(perf);assert.deepEqual(out.bytes,bytes);report.performance.push({bytes:bytes.length,openMs:opened,roundTripMs:Date.now()-start});}
  const long=Buffer.from('x'.repeat(1024*1024));await open(perf,'long-line.txt',long);assert.deepEqual((await download(perf)).bytes,long);check('100 KiB / 1 MiB / 5 MiB / 10 MiB round trips and 1 MiB single line');await perfContext.close();
  const macContext=await browser.newContext();await macContext.addInitScript(()=>{Object.defineProperty(navigator,'platform',{get:()=> 'MacIntel'});window.showSaveFilePicker=undefined;});const mp=await macContext.newPage();await mp.goto(url);await mp.locator('#emptyNew').click();await editor(mp).fill('Mac shortcut');const md=await readDownload(mp,()=>mp.keyboard.press('Meta+s'));assert.equal(md.bytes.toString(),'Mac shortcut');await macContext.close();check('Mac Command+S mapping (platform simulated)');
  await waitSaved(p);await p.locator('#actionsOpen').click();await p.locator('#fresh').click();await p.locator('#confirmYes').click();await p.locator('#empty').waitFor();await waitSaved(p);await p.reload();await p.locator('#empty').waitFor();check('Fresh Start persists an empty workspace');
  assert.deepEqual(report.errors,[]);check('No uncaught browser errors');report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/failure.png'}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync('docs/browser-results.json',JSON.stringify(report,null,2));await browser.close();server.close();}
