// Optional: pass TYPEBENCH_BASELINE_DIR pointing to the unpacked v0.1.0 release.
import {chromium as pw} from 'playwright';import chromium from '@sparticuz/chromium';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const version=JSON.parse(fs.readFileSync('package.json')).version;const baseline=process.env.TYPEBENCH_BASELINE_DIR;if(!baseline)throw new Error('Set TYPEBENCH_BASELINE_DIR to the unpacked v0.1.0 release.');
let root=path.resolve(baseline);const current=process.cwd();
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://localhost').pathname;if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/')){res.writeHead(403);res.end();return;}fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(f)]||'text/plain','Cache-Control':'no-cache'});res.end(e?'':b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await pw.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||await chromium.executablePath(),args:chromium.args.filter(x=>!['--single-process','--disable-web-security','--allow-running-insecure-content','--disable-site-isolation-trials'].includes(x))});const ctx=await browser.newContext({acceptDownloads:true});let p=await ctx.newPage();p.on('dialog',d=>d.accept());const url=`http://127.0.0.1:${server.address().port}/`;
try{
 await p.goto(url);const baselineVersion=await p.locator('.version').innerText();assert(/^v0\.[12]\.0$/.test(baselineVersion));const original=Buffer.from('v0.1.0 working copy\r\nUnicode café 🛠️\nlast  ');await p.locator('#filePicker').setInputFiles({name:'existing-work.txt',mimeType:'text/plain',buffer:original});await p.waitForFunction(()=>document.getElementById('filePath').textContent==='existing-work.txt');await p.waitForFunction(()=>document.getElementById('browserStatus').textContent.includes('Saved in this browser'));await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');
 root=current;await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await p.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting);const workers=ctx.serviceWorkers();let nextWorker;for(const worker of workers){if(await worker.evaluate(v=>typeof CACHE==='string'&&CACHE.includes(v+'-'),version))nextWorker=worker;}assert(nextWorker);await p.close();
 await nextWorker.evaluate(()=>new Promise((resolve,reject)=>{const start=Date.now();const timer=setInterval(()=>{if(!self.registration.waiting&&self.registration.active?.state==='activated'){clearInterval(timer);resolve(true);}else if(Date.now()-start>10000){clearInterval(timer);reject(new Error('Update did not activate after all clients closed.'));}},50);}));
 p=await ctx.newPage();p.on('dialog',d=>d.accept());await p.goto(url);await p.waitForFunction(v=>document.querySelector('.version').textContent==='v'+v,version);await p.waitForFunction(()=>document.getElementById('filePath').textContent==='existing-work.txt');const dl=p.waitForEvent('download');await p.locator('#download').click();assert.deepEqual(fs.readFileSync(await (await dl).path()),original);await p.locator('#settingsOpen').click();assert.equal(await p.locator('#indentStyle').inputValue(),'spaces');assert.equal(await p.locator('#tabIndents').isChecked(),false);await p.locator('#settingsDialog [data-close]').click();await p.locator('#findOpen').click();await p.locator('#findQuery').fill('working');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='1 match');
 const result={version,baselineVersion,success:true,checks:[baselineVersion+' browser workspace survives service-worker upgrade to v'+version+' byte-for-byte','New settings receive safe defaults and search runs after upgrade']};fs.writeFileSync('docs/compatibility-'+baselineVersion+'-results.json',JSON.stringify(result,null,2));console.log(result);
}finally{await browser.close();server.close();}
