import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
import {harness,waitSaved,open,download,command} from './harness.mjs';
const {p,url,report,check,finish}=await harness('context-brackets');
const editor=()=>p.locator('.cm-content');
async function text(){return (await download(p)).bytes.toString();}
async function menu(name){await p.locator('.file-row').filter({hasText:name}).click({button:'right'});await p.locator('#fileMenu').waitFor({state:'visible'});}
try{
 await p.goto(url);await waitSaved(p);await open(p,'first.pde','void setup() {}\r\n// café');await open(p,'second.ino','void loop() {}');
 await menu('first.pde');assert.equal(await p.locator('#filePath').textContent(),'second.ino');await p.locator('#fileMenu [data-file-action=duplicate]').click();assert.equal(await p.locator('#filePath').textContent(),'first (2).pde');assert.equal(await text(),'void setup() {}\r\n// café');assert.equal(await p.locator('#language').inputValue(),'processing');check('Right-click duplicates the targeted inactive file with exact source and language');
 await menu('second.ino');await p.locator('#fileMenu [data-file-action=rename]').click();await p.locator('#nameInput').fill('sketches/renamed.ino');await p.locator('#nameForm [type=submit]').click();assert.equal(await p.locator('#filePath').textContent(),'sketches/renamed.ino');assert.equal(await p.locator('#language').inputValue(),'arduino');check('Context rename targets the clicked file and preserves relative paths');
 await menu('first.pde');const d=await download(p,'#fileMenu [data-file-action=download]');assert.equal(d.name,'first.pde');assert.equal(d.bytes.toString(),'void setup() {}\r\n// café');assert.equal(await p.locator('#filePath').textContent(),'sketches/renamed.ino');await p.evaluate(()=>window.showSaveFilePicker=undefined);await menu('first.pde');const saved=await download(p,'#fileMenu [data-file-action=save]');assert.equal(saved.name,'first.pde');assert.equal(saved.bytes.toString(),'void setup() {}\r\n// café');assert.equal(await p.locator('#filePath').textContent(),'sketches/renamed.ino');check('Context download and fallback Save export the inactive target without switching documents');
 await menu('first (2).pde');await p.locator('#fileMenu [data-file-action=delete]').click();assert.equal(await p.locator('.file-row').filter({hasText:'first (2).pde'}).count(),0);assert.equal(await p.locator('#closedCount').textContent(),'1');await p.locator('#recover').click();await p.locator('#recoveryList button').filter({hasText:'first (2).pde'}).click();assert.equal(await text(),'void setup() {}\r\n// café');check('Delete from workspace is recoverable and leaves other files intact');
 await p.locator('[role=tab]').filter({hasText:'renamed.ino'}).click({button:'right'});await p.locator('#fileMenu [data-file-action=open]').click();assert.equal(await p.locator('#filePath').textContent(),'sketches/renamed.ino');
 const row=p.locator('.file-row').filter({hasText:'first.pde'});await row.focus();await p.keyboard.press('Shift+F10');assert(await p.locator('#fileMenu').isVisible());await p.keyboard.press('End');assert.equal(await p.locator(':focus').getAttribute('data-file-action'),'delete');await p.keyboard.press('Home');assert.equal(await p.locator(':focus').getAttribute('data-file-action'),'open');await p.keyboard.press('r');assert.equal(await p.locator(':focus').getAttribute('data-file-action'),'rename');await p.keyboard.press('Escape');assert(await row.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+F10');await p.keyboard.press('Tab');assert(await p.locator('#fileMenu').isHidden());await row.focus();await p.keyboard.press('F2');assert.equal(await p.locator('#nameInput').inputValue(),'first.pde');await p.locator('#nameDialog [data-close]').first().click();check('Tab context menus, Shift+F10, F2, arrows, typeahead, Escape, and focus return');
 for(const theme of ['dark','light','contrast']){await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption(theme);await p.locator('#settingsDialog [data-close]').click();await menu('first.pde');const a=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();if(a.violations.length)console.log(JSON.stringify(a.violations,null,2));assert.deepEqual(a.violations.map(v=>v.id),[]);await p.screenshot({path:`docs/screenshots/file-menu-${theme}.png`});await p.keyboard.press('Escape');}check('File menus pass automated accessibility checks in all three themes');
 await p.setViewportSize({width:320,height:740});await p.locator('#fileActions').click();let r=await p.locator('#fileMenu').boundingBox();assert(r.x>=0&&r.x+r.width<=320);await p.screenshot({path:'docs/screenshots/file-menu-mobile-320.png'});await p.keyboard.press('Escape');await p.setViewportSize({width:1440,height:1000});check('Touch-friendly file action button stays within a 320 px viewport');
 await open(p,'brackets.js','');await editor().focus();await p.keyboard.type('(');assert.equal(await text(),'()');assert.equal(await p.locator('#cursor').textContent(),'Ln 1, Col 2');await editor().focus();await p.keyboard.type(')');assert.equal(await text(),'()');assert.equal(await p.locator('#cursor').textContent(),'Ln 1, Col 3');await editor().focus();await p.keyboard.type('[');assert.equal(await text(),'()[]');await editor().focus();await p.keyboard.press('Backspace');assert.equal(await text(),'()');await p.locator('#undo').click();assert.equal(await text(),'()[]');await p.locator('#redo').click();assert.equal(await text(),'()');check('Bracket insertion, closer skipping, paired deletion, and undo/redo');
 await editor().press('Control+a');await p.keyboard.type('{');assert.equal(await text(),'{()}');await p.locator('#undo').click();assert.equal(await text(),'()');check('Typing an opener wraps selected text and undoes as one operation');
 await open(p,'new-brackets.ino','');await editor().focus();await p.keyboard.type('{');await p.keyboard.press('Enter');const braced=await text();assert(braced.startsWith('{\n'));assert(braced.endsWith('\n}'));assert.equal(await p.locator('#cursor').textContent(),'Ln 2, Col 3');check('Arduino braces combine with automatic indentation and a matching closing line');
 await open(p,'new-brackets.pde','void draw() {\r\n  circle(10, 10, 20);\r\n}');await editor().press('Control+End');await p.keyboard.type('[');const raw=await text();assert.equal(raw,'void draw() {\r\n  circle(10, 10, 20);\r\n}[]');check('Processing bracket completion preserves existing CRLF bytes');
 await p.locator('#settingsOpen').click();await p.locator('#autoBrackets').uncheck();await p.locator('#settingsDialog [data-close]').click();await open(p,'literal.txt','');await editor().focus();await p.keyboard.type('([{');assert.equal(await text(),'([{');await waitSaved(p);await p.reload();await p.locator('#settingsOpen').click();assert(!(await p.locator('#autoBrackets').isChecked()));await p.locator('#autoBrackets').check();await p.locator('#settingsDialog [data-close]').click();await open(p,'quotes.txt','');await editor().focus();await p.keyboard.type("'");assert.equal(await text(),"'");check('Bracket setting persists and can be disabled; quotes are not auto-paired');
 await open(p,'paste.js','const braces = {nested: []};\r\n');assert.equal(await text(),'const braces = {nested: []};\r\n');check('Importing complete code never adds or changes brackets');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/context-brackets-failure.png'});process.exitCode=1;}finally{await finish();}
