import {chromium as playwright} from 'playwright';
import chromium from '@sparticuz/chromium';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import assert from 'node:assert/strict';
import {encodeText} from '../src/core.js';
const root=path.resolve('.'), report={version:JSON.parse(fs.readFileSync('package.json')).version,date:'2026-10-01',checks:[],performance:[],errors:[]};
fs.mkdirSync('docs/screenshots',{recursive:true});
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let filename=decodeURIComponent(u.pathname).replace(/^\/typebench\//,'/');if(filename.endsWith('/'))filename+='index.html';const full=path.resolve(root,'.'+filename);if(!full.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(full,(e,data)=>{if(e){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.md':'text/plain'})[path.extname(full)]||'text/plain');res.end(data);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}/typebench/`;
const browser=await playwright.launch({executablePath:process.env.CHROMIUM_EXECUTABLE || await chromium.executablePath(),args:chromium.args.filter(x=>!['--single-process','--disable-web-security','--allow-running-insecure-content','--disable-site-isolation-trials'].includes(x)),headless:true});
report.browser=browser.version();
const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true});
const p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push(e.message));p.on('dialog',d=>d.accept());
const check=(name)=>{report.checks.push(name);console.log('PASS',name);};
const waitSaved=page=>page.waitForFunction(()=>document.getElementById('browserStatus').textContent.includes('Saved in this browser'));
const editor=page=>page.locator('.cm-content');
async function readDownload(page,action){const promise=page.waitForEvent('download');await action();const d=await promise;return {name:d.suggestedFilename(),bytes:fs.readFileSync(await d.path())};}
async function download(page){return readDownload(page,()=>page.locator('#download').click());}
async function open(page,name,buffer){await page.locator('#filePicker').setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.from(buffer)});await page.waitForFunction(name=>document.getElementById('filePath').textContent===name,name);}
try{
  await p.goto(url);await waitSaved(p);await p.locator('#modeToggle').click();
  const original=Buffer.from('cat Cat cats\r\ncat\nR12 R99\rtail  ');
  await open(p,'find-workshop.txt',original);await p.keyboard.press('Control+f');await p.locator('#findQuery').fill('cat');
  await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='4 matches');assert(await p.locator('.cm-search-match').count()>=4);await p.locator('#findWord').check();await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='3 matches');await p.locator('#findCase').check();await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='2 matches');
  await p.locator('#findNext').click();assert.equal(await p.locator('#findStatus').textContent(),'1 of 2 matches');await p.locator('#findPrev').click();assert.equal(await p.locator('#findStatus').textContent(),'2 of 2 matches');check('Find highlights, case, whole word, and wrapping navigation');
  await p.locator('#replaceQuery').fill('dog');await p.waitForFunction(()=>!document.getElementById('replaceAll').disabled);await p.locator('#replaceAll').click();assert.equal((await download(p)).bytes.toString(),'dog Cat cats\r\ndog\nR12 R99\rtail  ');await p.locator('#undo').click();assert.deepEqual((await download(p)).bytes,original);await p.locator('#redo').click();assert.equal((await download(p)).bytes.toString(),'dog Cat cats\r\ndog\nR12 R99\rtail  ');check('Replace All is one undo/redo operation with mixed endings intact');
  await p.locator('#findQuery').fill('cats');await p.locator('#replaceQuery').fill('kittens');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='1 match');await p.locator('#replaceOne').click();assert((await download(p)).bytes.toString().includes('kittens'));await p.locator('#undo').click();check('Replace acts on the next match with one click');
  await p.locator('#findWord').uncheck();await p.locator('#findCase').uncheck();await p.locator('#regexDetails summary').click();await p.locator('#findRegex').check();await p.locator('#findQuery').fill('R(\\d+)');await p.locator('#replaceQuery').fill('pin_$1');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='2 matches');await p.locator('#replaceAll').click();assert((await download(p)).bytes.toString().includes('pin_12 pin_99'));check('Advanced regex capture replacement');
  await p.locator('#findQuery').fill('[');await p.waitForFunction(()=>document.getElementById('findStatus').textContent.includes('Invalid expression'));assert(await p.locator('#replaceAll').isDisabled());await p.locator('#findQuery').fill('^');await p.locator('#replaceQuery').fill('> ');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='4 matches');await p.locator('#replaceAll').click();assert((await download(p)).bytes.toString().startsWith('> dog'));await p.locator('#undo').click();check('Invalid regex feedback and zero-width replacement');
  await p.locator('#findClose').click();await p.keyboard.press('Control+Shift+p');await p.locator('#commandQuery').fill('go to line');await p.locator('#commandQuery').press('Enter');await p.locator('#gotoInput').fill('2:3');await p.locator('#gotoForm [type=submit]').click();assert.equal(await p.locator('#cursor').textContent(),'Ln 2, Col 3');await p.keyboard.press('Control+g');await p.locator('#gotoInput').fill('99999');await p.locator('#gotoForm [type=submit]').click();assert((await p.locator('#gotoError').textContent()).includes('Enter a line'));await p.locator('#gotoDialog [data-close]').first().click();check('Searchable keyboard command menu and validated go-to-line');
  const js=Buffer.from('const light = 1;\r\nconst motor = 2;\nconsole.log(light, motor);');await open(p,'workshop.js',js);await editor(p).press('Control+a');await p.keyboard.press('Control+]');assert((await download(p)).bytes.toString().startsWith('  const'));await p.locator('#undo').click();assert.deepEqual((await download(p)).bytes,js);await editor(p).press('Control+a');await p.keyboard.press('Control+/');assert((await download(p)).bytes.toString().startsWith('// const'));await p.locator('#undo').click();assert.deepEqual((await download(p)).bytes,js);check('Indent and comment shortcuts preserve source and undo cleanly');
  await p.keyboard.press('Control+g');await p.locator('#gotoInput').fill('2');await p.locator('#gotoForm [type=submit]').click();await p.keyboard.press('Alt+ArrowUp');assert.equal((await download(p)).bytes.toString(),'const motor = 2;\r\nconst light = 1;\nconsole.log(light, motor);');await p.locator('#undo').click();await p.keyboard.press('Alt+Shift+ArrowDown');assert((await download(p)).bytes.toString().includes('const motor = 2;\r\nconst motor = 2;'));await p.locator('#undo').click();assert.deepEqual((await download(p)).bytes,js);check('Move and duplicate line shortcuts with mixed EOL');
  await p.locator('#settingsOpen').click();await p.locator('#indentStyle').selectOption('tabs');await p.locator('#tabSize').selectOption('4');await p.locator('#tabIndents').check();await p.locator('#whitespace').check();await p.locator('#settingsDialog [data-close]').click();assert.deepEqual((await download(p)).bytes,js);await p.locator('#new').click();await editor(p).focus();await p.keyboard.press('Tab');await p.keyboard.type('literal tab');assert.equal((await download(p)).bytes.toString(),'\tliteral tab');assert(await p.locator('.cm-highlightTab').count()>0);await p.keyboard.press('Escape');await p.keyboard.press('Tab');assert(!(await p.evaluate(()=>document.activeElement.classList.contains('cm-content'))));check('Tab insertion, whitespace display, and keyboard escape');
  await waitSaved(p);await p.reload();await p.locator('#settingsOpen').click();assert.equal(await p.locator('#indentStyle').inputValue(),'tabs');assert(await p.locator('#whitespace').isChecked());assert(await p.locator('#tabIndents').isChecked());await p.locator('#settingsDialog [data-close]').click();check('New settings survive reload');
  await open(p,'slow-pattern.txt',Buffer.from('a'.repeat(200)+'!'));await p.locator('#findOpen').click();await p.locator('#regexDetails summary').click();await p.locator('#findRegex').check();await p.locator('#findQuery').fill('(a+)+$');await p.waitForFunction(()=>document.getElementById('findStatus').textContent.includes('took too long'));assert((await download(p)).bytes.toString().endsWith('!'));await p.locator('#findQuery').fill('a+');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='1 match');check('Pathological regex times out without blocking editor or download');
  await p.locator('#findQuery').fill('(a+)+$');await p.locator('#findCancel').click();assert((await p.locator('#findStatus').textContent()).includes('cancelled'));await p.locator('#findClose').click();check('Search can be cancelled');
  await open(p,'search-matches.txt',Buffer.from('alpha alpha'));await p.locator('#findOpen').click();await p.locator('#findQuery').fill('alpha');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='2 matches');await p.locator('#new').click();await editor(p).fill('beta');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='No matches');assert(await p.locator('#replaceAll').isDisabled());assert.equal((await download(p)).bytes.toString(),'beta');check('Switching documents invalidates stale replacement results');
  await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();await p.locator('#findOpen').click();await p.locator('#findQuery').fill('beta');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='1 match');await p.locator('#replaceQuery').fill('offline replace');await p.waitForFunction(()=>!document.getElementById('replaceAll').disabled);await p.locator('#replaceAll').click();assert.equal((await download(p)).bytes.toString(),'offline replace');await context.setOffline(false);check('Search worker and replacement work after offline reload');
  await p.locator('#findClose').click();await open(p,'workshop-review.js',Buffer.from('// Lights on the bench\nconst light = 1;\nconst motor = 2;\nconst sensor = 3;\n\nfunction setup() {\n  console.log(light, motor, sensor);\n}\n'));await p.locator('#findOpen').click();await p.locator('#findQuery').fill('const');await p.locator('#replaceQuery').fill('let');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='3 matches');
  for(const theme of ['dark','light','contrast']){await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption(theme);await p.locator('#settingsDialog [data-close]').click();await p.screenshot({path:`docs/screenshots/search-${theme}.png`});}
  await p.locator('#findClose').click();await p.keyboard.press('Control+Shift+p');await p.locator('#commandQuery').fill('line');await p.screenshot({path:'docs/screenshots/commands.png'});await p.keyboard.press('Escape');await p.setViewportSize({width:390,height:844});if(await p.locator('#sidebarToggle').getAttribute('aria-expanded')==='true')await p.locator('#sidebarToggle').click();await p.locator('#findOpen').click();await p.locator('#findQuery').fill('const');await p.waitForFunction(()=>document.getElementById('findStatus').textContent==='3 matches');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'docs/screenshots/search-mobile.png'});check('Search and commands visual review across themes and mobile');
  assert.deepEqual(report.errors,[]);check('No uncaught editing workflow errors');report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/editing-failure.png'}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync('docs/editing-browser-results.json',JSON.stringify(report,null,2));await browser.close();server.close();}
