import assert from 'node:assert/strict';
import {unzipSync} from 'fflate';
import {harness,open,download,waitSaved,command} from './harness.mjs';
const {p,url,context,report,check,finish}=await harness('files');
try{
 await p.goto(url);await waitSaved(p);
 // Real browser FileSystemFileHandles from OPFS; only the OS chooser is substituted.
 await p.evaluate(async()=>{const root=await navigator.storage.getDirectory();window.testHandle=await root.getFileHandle('native.ino',{create:true});const w=await testHandle.createWritable();await w.write('void setup() {}\r\nvoid loop() {}\n');await w.close();window.showOpenFilePicker=async()=>[testHandle];window.showSaveFilePicker=async()=>testHandle;});
 await command(p,'Open files with direct saving');await p.waitForFunction(()=>document.getElementById('filePath').textContent==='native.ino');assert.equal(await p.locator('#language').inputValue(),'arduino');await p.locator('.cm-content').press('Control+End');await p.keyboard.type('// edited');await p.locator('#saveFile').click();await p.waitForFunction(()=>document.getElementById('fileStatus').textContent==='Saved to a file');assert.equal(await p.evaluate(async()=>await (await testHandle.getFile()).text()),'void setup() {}\r\nvoid loop() {}\n// edited');check('Permission-based open and direct write with real browser file handles');
 await p.evaluate(async()=>{const w=await testHandle.createWritable();await w.write('// outside edit');await w.close();});await p.locator('#saveFile').click();await p.locator('#confirmDialog button[value=cancel]').last().click();assert.equal(await p.evaluate(async()=>await (await testHandle.getFile()).text()),'// outside edit');await p.locator('#saveFile').click();await p.locator('#confirmYes').click();await p.waitForFunction(()=>!document.getElementById('saveFile').disabled);assert((await p.evaluate(async()=>await (await testHandle.getFile()).text())).includes('// edited'));check('External disk edits require explicit overwrite approval');
 await p.evaluate(()=>{window.realCreate=testHandle.createWritable.bind(testHandle);testHandle.createWritable=async()=>{const stream=await realCreate();return {write:b=>stream.write(b),close:async()=>{await new Promise(r=>window.releaseWrite=r);return stream.close();},abort:()=>stream.abort()};};});await p.locator('#saveFile').click();await p.waitForFunction(()=>typeof window.releaseWrite==='function');await command(p,'Rename document');await p.locator('#nameInput').fill('renamed.ino');await p.locator('#nameForm [type=submit]').click();await p.evaluate(()=>releaseWrite());await p.waitForFunction(()=>!document.getElementById('saveFile').disabled);await p.evaluate(()=>{testHandle.createWritable=realCreate;window.pickerCalled=false;window.showSaveFilePicker=async()=>{pickerCalled=true;return testHandle;};});await p.locator('#saveFile').click();await p.waitForFunction(()=>window.pickerCalled&&!document.getElementById('saveFile').disabled);check('Renaming during an in-flight write leaves the next Save asking for a destination');
 await p.evaluate(()=>window.showSaveFilePicker=async()=>{throw new DOMException('No permission','NotAllowedError')});await command(p,'Save as');assert((await p.locator('#bannerText').textContent()).includes('Could not save'));assert((await download(p)).bytes.toString().includes('// edited'));check('Permission failure preserves working text and download fallback');
 await p.evaluate(()=>window.showSaveFilePicker=undefined);const fallback=p.waitForEvent('download');await p.locator('#saveFile').click();const d=await fallback;assert.equal(d.suggestedFilename(),'native.ino');check('Save falls back to download on unsupported browsers');
 await open(p,'paths.md','# Paths\r\nUnicode: café 🛠️\n');await command(p,'Rename document');await p.locator('#nameInput').fill('notes/paths.md');await p.locator('#nameForm [type=submit]').click();const promise=p.waitForEvent('download');await command(p,'Export workspace documents as ZIP');const zip=await promise;const fs=await import('node:fs');const content=unzipSync(fs.readFileSync(await zip.path()));assert.equal(Buffer.from(content['notes/paths.md']).toString(),'# Paths\r\nUnicode: café 🛠️\n');assert(Buffer.from(content['native.ino']).toString().includes('// edited'));check('Workspace ZIP preserves relative paths, Unicode and mixed endings');
 await command(p,'Close document');await p.locator('#recover').click();await p.locator('#recoveryList button').first().click();assert.equal((await download(p)).bytes.toString(),'# Paths\r\nUnicode: café 🛠️\n');check('Closed documents recover intact after file export');
 await p.locator('#settingsOpen').click();assert(!await p.locator('#tabSize').isVisible());await p.locator('#settingsDialog [data-close]').click();await p.locator('#modeToggle').click();await p.locator('#settingsOpen').click();assert(await p.locator('#tabSize').isVisible());await p.locator('#tabSize').selectOption('4');await p.locator('#settingsDialog [data-close]').click();await waitSaved(p);await p.reload();assert.equal(await p.locator('#modeToggle').textContent(),'Advanced');check('Easy/Advanced exposes deeper controls and persists without changing documents');
 await command(p,'Open an example');await p.locator('[data-example=processing]').click();assert.equal(await p.locator('#filePath').textContent(),'Orbit.pde');assert(await p.locator('.cm-content .tok-func').count());await p.screenshot({path:'docs/screenshots/processing.png'});check('Optional Processing example is explicitly loaded and editable');
 await command(p,'Fresh Start');await p.locator('#confirmYes').click();await waitSaved(p);assert.equal(await p.locator('#documentCount').textContent(),'0');await p.reload();assert(await p.locator('#empty').isVisible());check('Fresh Start removes examples and restores an empty workspace');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/files-failure.png'});process.exitCode=1;}finally{await finish();}
