import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {unzipSync} from 'fflate';
import {harness,waitSaved,open,download,command} from './harness.mjs';
const {p,url,report,check,finish}=await harness('folder-boundaries');
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),'typebench-recovery-')),root=path.join(fixture,'Example');fs.mkdirSync(root);fs.writeFileSync(path.join(root,'main.ino'),'void setup() {}\r\n');
async function complete(){await p.waitForFunction(()=>!document.getElementById('folderImportDone').hidden);}
try{
 await p.goto(url);await waitSaved(p);await open(p,'keep.txt','keep this work');
 await p.evaluate(()=>{
  let batch=0;const directory={name:'Slow',isDirectory:true,createReader:()=>({readEntries:resolve=>resolve(batch++?[]:Array.from({length:20},(_,i)=>({name:`file${i}.txt`,isDirectory:false,file:resolve=>setTimeout(()=>resolve(new File(['text'],`file${i}.txt`)),100)})))})};
  const e=new Event('drop',{bubbles:true,cancelable:true});Object.defineProperty(e,'dataTransfer',{value:{types:['Files'],items:[{kind:'file',webkitGetAsEntry:()=>directory,getAsFile:()=>null}],files:[]}});document.dispatchEvent(e);
 });
 await p.locator('#folderImportCancel').click();await complete();assert.equal(await p.locator('#folderImportTitle').textContent(),'Import cancelled');await p.locator('#folderImportDone').click();let data=JSON.parse((await download(p,'#backup')).bytes);assert.equal(data.documents.length,1);assert.equal(data.folders.length,0);check('Cancelling an in-progress recursive import leaves all existing workspace data intact');
 await p.evaluate(()=>{window.originalTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(n,m,...r){if(m==='readwrite')throw new DOMException('Simulated storage full','QuotaExceededError');return originalTransaction.call(this,n,m,...r);};});await p.locator('#folderPicker').setInputFiles(root);await complete();await p.waitForFunction(()=>document.getElementById('folderImportBrowserStatus').textContent.includes('failed'));await p.locator('#folderImportDone').click();data=JSON.parse((await download(p,'#emergencyExport')).bytes);assert(data.folders.includes('Example'));assert(data.documents.some(d=>d.name==='Example/main.ino'));await p.evaluate(()=>IDBDatabase.prototype.transaction=window.originalTransaction);await p.locator('#retryStorage').click();await waitSaved(p);await p.reload();assert.equal(await p.getByRole('button',{name:'Folder Example',exact:true}).count(),1);check('Storage failure exposes recovery export containing the whole imported folder; retry survives refresh');
 const invalid=JSON.parse((await download(p,'#backup')).bytes);invalid.folders.push('../outside');await p.locator('#workspacePicker').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await p.waitForFunction(()=>document.getElementById('bannerText').textContent.includes('Workspace import failed'));assert.equal(await p.getByRole('button',{name:'Folder Example',exact:true}).count(),1);await p.locator('#dismissBanner').click();check('Unsafe folder paths in workspace JSON are rejected before replacement');
 await p.getByRole('button',{name:'Folder actions for Example',exact:true}).click();await p.locator('#folderMenu [data-file-action=import]').click();await p.locator('#folderPicker').setInputFiles(root);await complete();await p.locator('#folderImportDone').click();data=JSON.parse((await download(p,'#backup')).bytes);assert(data.documents.some(d=>d.name==='Example/Example/main.ino'));check('Import folder here uses the chosen parent while preserving the imported root');
 await p.getByRole('button',{name:'Folder actions for Example',exact:true}).click();await p.locator('#folderMenu [data-file-action=newMarkdown]').click();assert.equal(await p.locator('#filePath').textContent(),'Example/untitled.md');assert.equal(await p.locator('#language').inputValue(),'markdown');check('Folder context action creates a Markdown document in the correct parent');
 await command(p,'Fresh Start');await p.locator('#confirmYes').click();await waitSaved(p);await p.reload();assert.equal(await p.locator('.folder-row').count(),0);assert.equal(await p.locator('#documentCount').textContent(),'0');check('Fresh Start clears active and recovered folders durably');
 await p.locator('#newFolder').click();await p.locator('#folderNameInput').fill('Only/empty');await p.locator('#folderNameSubmit').click();const z=p.waitForEvent('download');await command(p,'Export workspace documents as ZIP');assert.deepEqual(Object.keys(unzipSync(fs.readFileSync(await (await z).path()))),['Only/','Only/empty/']);
 await p.getByRole('button',{name:'Folder actions for Only',exact:true}).click();await p.locator('#folderMenu [data-file-action=delete]').click();await p.locator('#confirmYes').click();const removed=(await download(p,'#backup')).bytes;assert.equal(JSON.parse(removed).closedFolders[0].documentIds.length,0);await command(p,'Fresh Start');await p.locator('#confirmYes').click();await p.locator('#workspacePicker').setInputFiles({name:'empty-folders.json',mimeType:'application/json',buffer:removed});await p.waitForFunction(()=>document.getElementById('closedCount').textContent==='1');await p.locator('#recover').click();await p.getByRole('button',{name:'Restore folder Only (0 files)',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Folder Only/empty',exact:true}).count(),1);assert.equal(await p.locator('#documentCount').textContent(),'0');check('Empty-folder-only ZIP and deleted empty-folder recovery survive workspace JSON round trips');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);process.exitCode=1;}finally{fs.rmSync(fixture,{recursive:true,force:true});await finish();}
