import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {unzipSync} from 'fflate';
import AxeBuilder from '@axe-core/playwright';
import {encodeText} from '../src/core.js';
import {harness,waitSaved,download,command} from './harness.mjs';
const {p,url,context,report,check,finish}=await harness('folders');
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),'typebench-folders-')),root=path.join(fixture,'Robot');
fs.mkdirSync(path.join(root,'src','drivers'),{recursive:true});fs.mkdirSync(path.join(root,'docs'),{recursive:true});fs.mkdirSync(path.join(root,'empty'),{recursive:true});
const raw='void setup() { pinMode(LED_BUILTIN, OUTPUT); }\r\nvoid loop() { digitalWrite(LED_BUILTIN, HIGH); }\n// café 🛠️  ';
fs.writeFileSync(path.join(root,'src','main.ino'),raw);fs.writeFileSync(path.join(root,'src','drivers','motor.cpp'),'// motor\r\n');fs.writeFileSync(path.join(root,'docs','notes.md'),'# Robot\n');fs.writeFileSync(path.join(root,'docs','encoded.txt'),encodeText('Unicode β 日本語\r\n','utf-16be',true));fs.writeFileSync(path.join(root,'diagram.svg'),'<svg xmlns="http://www.w3.org/2000/svg"></svg>');fs.writeFileSync(path.join(root,'firmware.ts'),'export const enabled = true;');fs.writeFileSync(path.join(root,'photo.png'),Buffer.from([137,80,78,71,0,0]));
async function readyImport(){await p.waitForFunction(()=>!document.getElementById('folderImportDone').hidden);}
async function done(){await p.locator('#folderImportDone').click();}
async function expand(){await command(p,'Expand all folders');}
async function folderMenu(name){await p.getByRole('button',{name:'Folder '+name,exact:true}).click({button:'right'});}
async function createFolder(name){await p.locator('#newFolder').click();await p.locator('#folderNameInput').fill(name);await p.locator('#folderNameSubmit').click();}
async function zip(){const pending=p.waitForEvent('download');await command(p,'Export workspace documents as ZIP');const d=await pending;return unzipSync(fs.readFileSync(await d.path()));}
async function nativeDrop(directory){const cdp=await context.newCDPSession(p),data={items:[],files:[directory],dragOperationsMask:1};await cdp.send('Input.dispatchDragEvent',{type:'dragEnter',x:500,y:300,data});await cdp.send('Input.dispatchDragEvent',{type:'dragOver',x:500,y:300,data});await cdp.send('Input.dispatchDragEvent',{type:'drop',x:500,y:300,data});await cdp.detach();}
try{
 await p.goto(url);await waitSaved(p);await createFolder('Project/src/empty');assert.equal(await p.locator('.folder-row').count(),3);await folderMenu('Project/src');await p.locator('#folderMenu [data-file-action=newFile]').click();assert.equal(await p.locator('#filePath').textContent(),'Project/src/untitled.txt');await p.locator('.cm-content').fill('local work\r\n');await command(p,'Rename document');await p.locator('#nameInput').fill('Project/src/readme.txt');await p.locator('#nameForm [type=submit]').click();await createFolder('Project/docs');check('Nested folder creation, empty folders, new files inside folders, and relative file moves');
 await folderMenu('Project/src');await p.locator('#folderMenu [data-file-action=rename]').click();await p.locator('#folderNameInput').fill('Project/lib');await p.locator('#folderNameSubmit').click();assert.equal(await p.locator('#filePath').textContent(),'Project/lib/readme.txt');assert.equal((await download(p)).bytes.toString(),'local work\n');assert(await p.getByRole('button',{name:'Folder Project/lib/empty',exact:true}).count());
 await folderMenu('Project/lib');await p.locator('#folderMenu [data-file-action=rename]').click();await p.locator('#folderNameInput').fill('Project/lib/child');await p.locator('#folderNameSubmit').click();assert((await p.locator('#folderNameError').textContent()).includes('inside itself'));await p.locator('#folderNameInput').fill('Project/docs');await p.locator('#folderNameSubmit').click();assert((await p.locator('#folderNameError').textContent()).includes('conflicts'));await p.locator('#folderNameDialog [data-close]').first().click();check('Folder rename/move changes descendants atomically and blocks collisions/cycles');
 const button=p.getByRole('button',{name:'Folder Project/lib',exact:true});await button.focus();await p.keyboard.press('ArrowLeft');assert.equal(await button.getAttribute('aria-expanded'),'false');await p.keyboard.press('Shift+F10');await p.keyboard.press('Escape');assert.equal(await button.getAttribute('aria-expanded'),'false');await waitSaved(p);await p.reload();assert.equal(await button.getAttribute('aria-expanded'),'false');await button.focus();await p.keyboard.press('ArrowRight');assert.equal(await button.getAttribute('aria-expanded'),'true');check('Collapse state persists, arrow navigation works, and context menus preserve disclosure state');
 await p.locator('#folderPicker').setInputFiles(root);await readyImport();assert((await p.locator('#folderImportStatus').textContent()).includes('Imported 6 text files'));assert((await p.locator('#folderImportLog').textContent()).includes('photo.png'));await done();await expand();await p.getByRole('button',{name:'Robot/src/main.ino',exact:true}).click();assert.equal(await p.locator('#language').inputValue(),'arduino');assert.equal((await download(p)).bytes.toString(),raw);const backup=JSON.parse((await download(p,'#backup')).bytes);assert(backup.documents.some(d=>d.name==='Robot/diagram.svg'&&d.language==='xml'));assert(backup.documents.some(d=>d.name==='Robot/firmware.ts'&&d.language==='typescript'));assert.equal(backup.documents.find(d=>d.name==='Robot/docs/encoded.txt').encoding,'utf-16be');check('Real directory picker imports nested text, Arduino, SVG/TypeScript, encodings, and reports binary skips');await p.screenshot({path:'docs/screenshots/folders-workspace.png'});
 await p.locator('#folderPicker').setInputFiles(root);await readyImport();assert((await p.locator('#folderImportLog').textContent()).includes('Robot → Robot (2)'));await done();assert((await download(p,'#backup')).bytes.toString().includes('Robot (2)/src/main.ino'));check('Repeated folder import keeps both complete hierarchies without overwriting');
 const dropped=path.join(fixture,'Dropped');fs.mkdirSync(path.join(dropped,'nested','empty'),{recursive:true});for(let i=0;i<125;i++)fs.writeFileSync(path.join(dropped,'f'+String(i).padStart(3,'0')+'.txt'),'file '+i+'\r\n');fs.writeFileSync(path.join(dropped,'nested','sketch.pde'),'void setup() { size(100,100); }');
 await nativeDrop(dropped);await readyImport();assert((await p.locator('#folderImportStatus').textContent()).includes('Imported 126 text files'));await done();const imported=JSON.parse((await download(p,'#backup')).bytes);assert(imported.folders.includes('Dropped/nested/empty'));assert.equal(imported.documents.filter(d=>d.name.startsWith('Dropped/')).length,126);check('Real browser directory drop drains more than 100 entries and preserves nested empty folders');
 const archive=await zip();assert.deepEqual(Buffer.from(archive['Robot/src/main.ino']),Buffer.from(raw));assert.deepEqual(archive['Robot/docs/encoded.txt'],encodeText('Unicode β 日本語\r\n','utf-16be',true));assert('Dropped/nested/empty/' in archive);assert('Project/lib/empty/' in archive);check('ZIP exports exact file bytes, relative paths, BOMs and explicit empty directories');
 await expand();await folderMenu('Robot');await p.locator('#folderMenu [data-file-action=delete]').click();await p.locator('#confirmDialog button[value=cancel]').last().click();assert(await p.getByRole('button',{name:'Folder Robot',exact:true}).count());await folderMenu('Robot');await p.locator('#folderMenu [data-file-action=delete]').click();await p.locator('#confirmYes').click();await p.getByRole('button',{name:'Folder Robot',exact:true}).waitFor({state:'detached'});assert.equal(await p.getByRole('button',{name:'Folder Robot',exact:true}).count(),0);await waitSaved(p);await p.reload();await createFolder('Robot');await p.locator('#recover').click();await p.locator('#recoveryList button').filter({hasText:'Restore folder Robot (6 files)'}).click();const recovered=JSON.parse((await download(p,'#backup')).bytes);assert(recovered.documents.some(d=>d.name==='Robot (3)/src/main.ino'&&d.raw===raw));assert.equal(recovered.closedFolders.length,0);check('Folder deletion is confirmed and recoverable across refresh; restoration avoids occupied paths');
 const roundTrip=(await download(p,'#backup')).bytes;await command(p,'Fresh Start');await p.locator('#confirmYes').click();await p.locator('#workspacePicker').setInputFiles({name:'folders.json',mimeType:'application/json',buffer:roundTrip});await p.waitForFunction(()=>Number(document.getElementById('documentCount').textContent)>100);assert(JSON.parse((await download(p,'#backup')).bytes).folders.includes('Dropped/nested/empty'));check('Workspace JSON round trip preserves folders, contents, recovery metadata and settings');
 await command(p,'Collapse all folders');for(const theme of ['dark','light','contrast']){await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption(theme);await p.locator('#settingsDialog [data-close]').click();await p.getByRole('button',{name:'Folder Project',exact:true}).click();await folderMenu('Project');const a=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();if(a.violations.length)console.log(JSON.stringify(a.violations,null,2));assert.deepEqual(a.violations.map(v=>v.id),[]);await p.screenshot({path:`docs/screenshots/folders-${theme}.png`});await p.keyboard.press('Escape');await command(p,'Collapse all folders');}check('Nested tree and folder menus pass automated accessibility checks across all themes');
 await p.setViewportSize({width:320,height:740});if(await p.locator('#sidebarToggle').getAttribute('aria-expanded')==='false')await p.locator('#sidebarToggle').click();await p.getByRole('button',{name:'Folder actions for Project',exact:true}).click();const bounds=await p.locator('#folderMenu').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=320);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'docs/screenshots/folders-mobile-320.png'});await p.keyboard.press('Escape');await p.setViewportSize({width:1440,height:1000});check('Folder tree and touch menus remain usable at 320 px');
 await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();await p.locator('#folderPicker').setInputFiles(root);await readyImport();assert((await p.locator('#folderImportStatus').textContent()).includes('Imported 6 text files'));await done();assert(Object.keys(await zip()).some(k=>k.includes('src/main.ino')));await context.setOffline(false);check('Nested workspace restores, imports local folders and exports ZIP after offline reload');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/folders-failure.png',timeout:5000}).catch(()=>{});process.exitCode=1;}finally{fs.rmSync(fixture,{recursive:true,force:true});await finish();}
