import assert from 'node:assert/strict';
import {allFolders,availablePath,assertAvailable,planFolderMove,validateFolderData} from '../src/folder-data.js';
import {droppedRoots,pickerRoots,captureDrop,binaryFile} from '../src/folder-import.js';
let count=0;async function test(name,fn){await fn();console.log('PASS',name);count++;}
await test('Folder ancestry retains explicit empty folders',()=>assert.deepEqual(allFolders(['Project/src/main.ino'],['Project/empty']),['Project','Project/empty','Project/src']));
await test('Namespace handles file/folder, case, ancestor and extension collisions',()=>{assert.equal(availablePath('Project','folder',[],['project']),'Project (2)');assert.equal(availablePath('a/b.txt','file',['a'],[]),'a (2)/b.txt');assert.equal(availablePath('Project/code.ino','file',['Project/code.ino'],[]),'Project/code (2).ino');assert.equal(availablePath('project/x','file',[],['Project']),'Project/x');assert.throws(()=>assertAvailable('Project','file',['Project/src/x'],[]));assert.throws(()=>assertAvailable('project/x','file',[],['Project']));});
await test('Folder move maps all descendants, preserves empty folders, prevents cycles/collisions',()=>{const p=planFolderMove('Project/src','Project/lib',['Project/src/a.ino','Project/readme.md'],['Project/src/empty']);assert(p.files.includes('Project/lib/a.ino'));assert(p.folders.includes('Project/lib/empty'));assert.throws(()=>planFolderMove('Project','Project/child',[],['Project']));assert.throws(()=>planFolderMove('Project/src','Project/lib',['Project/src/a','Project/lib/b'],[]));});
await test('Invalid folder data and mismatched recovery references are rejected',()=>{assert.deepEqual(validateFolderData({}),{folders:[],collapsedFolders:[],closedFolders:[]});for(const data of [{folders:['../outside']},{folders:['a','a']},{collapsedFolders:[4]},{closedFolders:[{id:'x',path:'A',folders:['A'],documentIds:['missing']}]}])assert.throws(()=>validateFolderData(data));});
await test('Folder recovery rejects shared document references and missing roots',()=>{const group=id=>({id,path:'A',folders:['A'],documentIds:['file']});assert.throws(()=>validateFolderData({closed:[{id:'file',name:'A/code.ino'}],closedFolders:[group('one'),group('two')]}));assert.throws(()=>validateFolderData({closed:[],closedFolders:[{id:'one',path:'A',folders:[],documentIds:[]}]}));});
await test('Picker groups files by root and preserves relative paths',()=>{const roots=pickerRoots([{name:'a.ino',webkitRelativePath:'Project/src/a.ino'}]);assert.deepEqual([...roots[0].folders],['Project','Project/src']);assert.equal(roots[0].files[0].path,'Project/src/a.ino');});
const entry=(name)=>({name,isDirectory:false,file:resolve=>resolve(new File(['text'],name))});
function directory(name,children,size=100){let calls=0;return {name,isDirectory:true,get calls(){return calls;},createReader(){let pos=0;return {readEntries(resolve){calls++;const batch=children.slice(pos,pos+size);pos+=batch.length;resolve(batch);}};}};}
await test('Recursive drop drains every directory batch, including empty folders',async()=>{const empty=directory('empty',[]),root=directory('Project',[...Array.from({length:251},(_,i)=>entry('f'+i+'.txt')),directory('nested',[entry('main.ino'),empty])]);const roots=await droppedRoots([{entry:root}],{signal:new AbortController().signal});assert.equal(roots[0].files.length,252);assert(root.calls>=4);assert(roots[0].folders.has('Project/nested/empty'));});
await test('Entry permission errors are recorded without dropping sibling files',async()=>{const bad={name:'blocked',isDirectory:true,createReader:()=>({readEntries:(r,reject)=>reject(new Error('Denied'))})};const roots=await droppedRoots([{entry:directory('Project',[bad,entry('good.txt')])}]);assert.equal(roots[0].files.length,1);assert.match(roots[0].errors[0].reason,/Denied/);});
await test('Cancel interrupts an unresolved directory read',async()=>{const controller=new AbortController(),root={name:'slow',isDirectory:true,createReader:()=>({readEntries(){}})};const p=droppedRoots([{entry:root}],{signal:controller.signal});controller.abort();await assert.rejects(p,{name:'AbortError'});});
await test('Drop handles are captured synchronously, with file and modern-handle fallback',async()=>{let captured=0;const handle={name:'Project',kind:'directory',async *values(){yield {name:'x.txt',kind:'file',getFile:()=>Promise.resolve(new File(['x'],'x.txt'))};}};const sources=captureDrop({items:[{kind:'file',getAsFileSystemHandle(){captured++;return Promise.resolve(handle);},getAsFile:()=>null}]});assert.equal(captured,1);const roots=await droppedRoots(sources);assert.equal(roots[0].files[0].path,'Project/x.txt');assert.equal(captureDrop({files:[new File(['a'],'a.txt')]}).length,1);});
await test('Text/source extensions take precedence over misleading binary MIME types',()=>{assert(!binaryFile({name:'main.ts',type:'video/mp2t'}));assert(!binaryFile({name:'diagram.svg',type:'image/svg+xml'}));assert(binaryFile({name:'image.png',type:'image/png'}));assert(!binaryFile({name:'Dockerfile',type:''}));});
console.log(count+' folder checks passed');
