import assert from 'node:assert/strict';
import {languageList,detectLanguage,fenceLanguage} from '../src/language-data.js';
import {highlightCode} from '../src/languages.js';
const samples={markdown:'# Heading\n\n**bold**',html:'<div class="a">Hello</div>',css:'body { color: red; }',javascript:'const s = `hello ${name}`; // note',typescript:'interface Point { x: number }',json:'{"name":"hello","count":4}',python:'"""multiline\nstring"""\ndef draw(x):\n  return 42',c:'#include <stdio.h>\nint main(void) { return 0; }',cpp:'/* comment\nblock */\nstd::string s = R"(raw\ntext)";',java:'public class Hello { String s = "hi"; }',csharp:'public class Hello { string s = @"multi\nline"; }',go:'package main\nfunc main() { println(`raw\ntext`) }',rust:'fn main() { let x = 2; /* comment */ }',php:'<?php echo "hello"; // note\n?>',ruby:'def hello\n puts "world"\nend',shell:'# comment\nfor i in 1 2; do echo "$i"; done',powershell:'<# multi\ncomment #>\nWrite-Host "hello"',sql:"SELECT * FROM things WHERE name = 'hello';",yaml:'name: hello\nitems:\n - one',toml:'[workshop]\nname = "hello"',xml:'<?xml version="1.0"?><workshop id="1"/>',processing:'/* setup PVector\nsize comment */\nPVector p;\nvoid setup() { size(640, 480); p = new PVector(10, 20); }\nvoid draw() { background(24); ellipse(p.x, p.y, 20, 20); }\nString s = "draw()";\nfloat angle = TWO_PI;',arduino:'#include <Arduino.h>\n/* digitalWrite HIGH\nmultiline comment */\nconst byte led = LED_BUILTIN;\nvoid setup() { pinMode(led, OUTPUT); Serial.begin(9600); }\nvoid loop() { digitalWrite(led, HIGH); int level = analogRead(A0); delay(100); digitalWrite(led, LOW); }\nString label = "pinMode HIGH";'};
for(const [id,label,ext] of languageList){for(const e of ext)assert.equal(detectLanguage('folder/test.'+e),id);if(id==='text')continue;const rendered=highlightCode(samples[id],id);assert(rendered.includes('class="tok-'),label+' has tokens');assert.equal(rendered.replace(/<[^>]*>/g,'').replaceAll('&quot;','"').replaceAll('&#39;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&'),samples[id],label+' preserves source');console.log('PASS',label);}
for(const [id,word,type] of [['processing','PVector','func'],['processing','size','func'],['processing','TWO_PI','num'],['arduino','pinMode','func'],['arduino','Serial','num'],['arduino','HIGH','num']])assert(highlightCode(samples[id],id).includes(`<span class="tok-${type}">${word}</span>`),word);
assert(highlightCode(samples.processing,'processing').includes('<span class="tok-comment">'));
assert.equal(fenceLanguage('ino'),'arduino');assert.equal(fenceLanguage('pde'),'processing');
assert.equal(highlightCode('<script>alert(1)</script>','text'),'&lt;script&gt;alert(1)&lt;/script&gt;');
console.log('PASS Processing and Arduino API tokens, multiline constructs, escaping and filename detection');
