import assert from 'node:assert/strict';
import {harness,open,download,waitSaved} from './harness.mjs';
const {p,url,context,report,check,finish}=await harness('markdown');
const preview=()=>p.waitForFunction(()=>document.getElementById('previewStatus').textContent==='Preview ready');
const source='# Workshop notebook\n\nA **bold** plan with _emphasis_, ~~obsolete notes~~, and [documentation](https://example.com).\n\n## Materials\n\n- [x] Arduino\n- [ ] Jumper wires\n\n| Part | Count |\n| --- | --- |\n| LED | 2 |\n\n> Measure twice.\n\n---\n\n```arduino\nvoid setup() { pinMode(LED_BUILTIN, OUTPUT); }\nvoid loop() { digitalWrite(LED_BUILTIN, HIGH); }\n```\n\n```processing\nPVector position;\nvoid setup() { size(640, 480); }\nvoid draw() { background(20); circle(mouseX, mouseY, 40); }\n```\n\n![Bench](https://images.example.test/bench.png)\n\n<script>window.pwned=true</script>\n<img src="https://evil.example.test/x" onerror="window.pwned=true">\n<iframe src="https://evil.example.test/frame"></iframe>\n<style>@import url(https://evil.example.test/style);</style>\n\n[bad](javascript:alert(1))\n';
let external=[];await context.route('https://**/*',route=>{external.push(route.request().url());return route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aM7sAAAAASUVORK5CYII=','base64')});});
try{
 await p.goto(url);await waitSaved(p);await open(p,'notebook.md',source);await p.locator('#viewsplit').click();await preview();
 assert.equal(await p.locator('#preview h1').textContent(),'Workshop notebook');assert.equal(await p.locator('#preview table tbody tr').count(),1);assert.equal(await p.locator('#preview input[type=checkbox]').count(),2);assert(await p.locator('#preview del').count());assert(await p.locator('#preview pre .tok-func').count());assert.equal(await p.locator('#preview script, #preview iframe, #preview style, #preview img').count(),0);assert.equal(await p.evaluate(()=>window.pwned),undefined);assert.equal(external.length,0);assert.equal(await p.locator('#preview a[href^="javascript:"]').count(),0);check('GFM preview, both sketch fences, scripts/HTML escaped and no silent resource requests');
 await p.locator('#preview .load-image').click();await p.locator('#confirmYes').click();await p.waitForFunction(()=>!!document.querySelector('#preview img')?.complete);assert.equal(external.length,1);assert(external[0].includes('images.example.test'));await p.locator('#blockImages').click();assert.equal(await p.locator('#preview img').count(),0);check('Image requests require explicit per-image permission and can be blocked again');
 const html=(await download(p,'#exportHTML')).bytes.toString();assert(html.includes('<table>'));assert(html.includes('tok-func'));assert(!html.includes('<script>'));assert(!html.includes('<img '));assert(html.includes("default-src 'none'"));assert.equal((await download(p)).bytes.toString(),source);check('Styled HTML export is safe and original Markdown download is exact');
 await p.locator('#outlineToggle').click();await p.locator('#outline button').filter({hasText:'Materials'}).click();assert.equal(await p.locator('#cursor').textContent(),'Ln 5, Col 1');await p.locator('#previewDivider').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#previewDivider').getAttribute('aria-valuenow'),'55');await p.locator('#syncScroll').check();await waitSaved(p);await p.reload();await preview();assert.equal(await p.locator('#previewDivider').getAttribute('aria-valuenow'),'55');assert(await p.locator('#syncScroll').isChecked());assert.equal(await p.locator('#editorArea').getAttribute('data-view'),'split');check('Heading navigation, keyboard divider, view and settings restoration');
 await open(p,'format.md','one\r\ntwo\nthree\r');await p.locator('.cm-content').press('Control+a');await p.locator('[data-format=quote]').click();assert.equal((await download(p)).bytes.toString(),'> one\r\n> two\n> three\r');await p.locator('#undo').click();assert.equal((await download(p)).bytes.toString(),'one\r\ntwo\nthree\r');await p.locator('.cm-content').press('Control+a');await p.locator('[data-format=bold]').click();assert.equal((await download(p)).bytes.toString(),'**one\r\ntwo\nthree\r**');await p.locator('#undo').click();check('Formatting is grouped and preserves mixed line endings');
 await open(p,'review.md',source.split('![Bench]')[0]);await p.locator('#viewsplit').click();await preview();for(const theme of ['dark','light','contrast']){await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption(theme);await p.locator('#settingsDialog [data-close]').click();await p.screenshot({path:`docs/screenshots/markdown-${theme}.png`});}
 await p.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));await p.emulateMedia({media:'print'});assert(await p.locator('#printDocument h1').isVisible());assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).colorScheme),'light');assert(!await p.locator('.topbar').isVisible());await p.pdf({path:'docs/print-sample.pdf',format:'A4',printBackground:true});await p.emulateMedia({media:'screen'});check('Clean Markdown print layout and PDF output');
 await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();await preview();assert(await p.locator('#preview table').count());assert((await download(p,'#exportHTML')).bytes.length>1000);await context.setOffline(false);check('Preview worker, syntax assets and HTML export work offline under a subdirectory');
 await p.setViewportSize({width:390,height:844});if(await p.locator('#sidebarToggle').getAttribute('aria-expanded')==='true')await p.locator('#sidebarToggle').click();await p.locator('#viewpreview').click();await preview();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'docs/screenshots/markdown-mobile.png'});await p.locator('#viewsource').click();assert(await p.locator('.cm-content').isVisible());check('Phone source and preview controls remain reachable without overflow');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/markdown-failure.png'});process.exitCode=1;}finally{await finish();}
