import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import {unzipSync} from 'fflate';
import {harness,waitSaved,download,command} from './harness.mjs';
const {p,url,context,report,check,finish}=await harness('package-smoke');
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),'typebench-package-')),folder=path.join(fixture,'Packaged');fs.mkdirSync(path.join(folder,'src'),{recursive:true});const source='void setup() {}\r\nvoid loop() {}\n';fs.writeFileSync(path.join(folder,'src','main.ino'),source);
try{
 await context.addInitScript(()=>{Object.defineProperty(navigator,'platform',{get:()=> 'MacIntel'});window.showSaveFilePicker=undefined;});
 const external=[];p.on('request',r=>{if(!r.url().startsWith(new URL(url).origin))external.push(r.url());});
 await p.goto(url);await waitSaved(p);assert.equal(await p.locator('.version').textContent(),'v'+JSON.parse(fs.readFileSync('package.json')).version);assert.equal(await p.locator('#commandNew kbd').textContent(),'⌘⌥N');assert.equal(await p.locator('#actionsOpen .shortcut').textContent(),'⌘⇧P');await p.locator('#emptyMarkdown').click();await p.locator('.cm-content').fill('# Packaged editor\n\n```arduino\nvoid setup() { pinMode(LED_BUILTIN, OUTPUT); }\n```\n');await p.waitForFunction(()=>document.getElementById('previewStatus').textContent==='Preview ready');assert(await p.locator('#preview .tok-func').count());
 await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();await p.waitForFunction(()=>document.getElementById('previewStatus').textContent==='Preview ready');const d=p.waitForEvent('download');await p.keyboard.press('Meta+s');assert((fs.readFileSync(await (await d).path())).toString().includes('pinMode'));assert((await download(p,'#exportHTML')).bytes.toString().includes('<h1'));await p.locator('.cm-content').press('Meta+a');await p.locator('#snippetCreate').click();await p.waitForFunction(()=>!document.getElementById('snippetPNG').disabled);assert((await download(p,'#snippetSVG')).bytes.toString().includes('pinMode'));assert((await download(p,'#snippetPNG')).bytes.length>1000);assert.deepEqual(external,[]);assert.deepEqual(report.errors,[]);
 await p.locator('#snippetDialog [data-close]').click();await p.locator('#folderPicker').setInputFiles(folder);await p.waitForFunction(()=>!document.getElementById('folderImportDone').hidden);assert((await p.locator('#folderImportStatus').textContent()).includes('Imported 1 text file'));await p.locator('#folderImportDone').click();await p.locator('#newFolder').click();await p.locator('#folderNameInput').fill('Packaged/empty');await p.locator('#folderNameSubmit').click();await waitSaved(p);await p.reload();assert.equal(await p.getByRole('button',{name:'Folder Packaged/src',exact:true}).count(),1);const z=p.waitForEvent('download');await command(p,'Export workspace documents as ZIP');const entries=unzipSync(fs.readFileSync(await (await z).path()));assert.equal(Buffer.from(entries['Packaged/src/main.ino']).toString(),source);assert('Packaged/empty/' in entries);assert.deepEqual(external,[]);assert.deepEqual(report.errors,[]);check('Extracted ZIP imports a nested folder offline, restores it after reload, and exports exact Arduino bytes and empty directories');
 const root=process.env.TYPEBENCH_PACKAGE_DIR||'.';report.runtimeSHA256=Object.fromEntries(['index.html','assets/app.js','assets/app.css','assets/search-worker.js','assets/markdown-worker.js','assets/zip-worker.js','assets/snippet-worker.js','sw.js'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));
 check('Extracted ZIP starts under a subdirectory, has Mac shortcut labels, previews Arduino, reloads offline and exports Markdown, SVG and PNG without external requests');report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);process.exitCode=1;}finally{fs.rmSync(fixture,{recursive:true,force:true});await finish();}
