import assert from 'node:assert/strict';
import {harness,open,download,waitSaved,command} from './harness.mjs';
import {encodeText} from '../src/core.js';
import {unzipSync} from 'fflate';
import fs from 'node:fs';
const {p,url,context,report,check,finish}=await harness('qualification');
try{
 await p.goto(url);await waitSaved(p);
 await p.evaluate(()=>{window.originalTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(n,m,...r){if(m==='readwrite')throw new DOMException('Simulated storage full','QuotaExceededError');return originalTransaction.call(this,n,m,...r);};});
 await p.locator('#emptyNew').click();await p.locator('.cm-content').fill('recover café 🛠️');await p.waitForFunction(()=>document.getElementById('retryStorage').hidden===false);assert(JSON.parse((await download(p,'#emergencyExport')).bytes).documents.some(d=>d.raw==='recover café 🛠️'));await p.evaluate(()=>IDBDatabase.prototype.transaction=originalTransaction);await p.locator('#retryStorage').click();await waitSaved(p);await p.reload();assert.equal((await download(p)).bytes.toString(),'recover café 🛠️');check('Failed storage write can export, retry, and recover after refresh');
 await command(p,'New Markdown');await p.locator('.cm-content').fill('# Alpha\n\n[Jump](#beta)\n\n## Beta\n\nText.');await p.waitForFunction(()=>document.getElementById('previewStatus').textContent==='Preview ready');assert.equal(await p.locator('#preview a').getAttribute('href'),'#tb-beta');assert(await p.locator('#preview #tb-beta').count());await p.locator('#viewpreview').click();await p.keyboard.press('Control+g');await p.locator('#gotoInput').fill('5');await p.locator('#gotoForm [type=submit]').click();assert.equal(await p.locator('#editorArea').getAttribute('data-view'),'split');check('Internal heading links work; go-to-line reveals source from preview');
 await p.locator('#tabs [aria-selected=true]').focus();await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#filePath').textContent(),'untitled.txt');await p.keyboard.press('Delete');assert.equal(await p.locator('#closedCount').textContent(),'1');await waitSaved(p);await p.reload();await p.locator('#recover').click();await p.locator('#recoveryList button').click();assert.equal((await download(p)).bytes.toString(),'recover café 🛠️');check('Keyboard tab switching/deletion and recovery survive refresh');
 await p.locator('#language').selectOption('rust');const bytes=(await download(p)).bytes;const imported=JSON.parse((await download(p,'#backup')).bytes);for(const d of imported.documents){d.fileHandle={fake:true};d.fileSaving=true;d.diskHash='untrusted';}const workspace=Buffer.from(JSON.stringify(imported));await p.locator('#workspacePicker').setInputFiles({name:'workspace.json',mimeType:'application/json',buffer:workspace});await p.locator('#confirmYes').click();await p.waitForFunction(()=>document.getElementById('language').value==='rust');assert.deepEqual((await download(p)).bytes,bytes);assert(!await p.locator('#saveFile').isDisabled());await command(p,'Detect language from filename');assert.equal(await p.locator('#language').inputValue(),'text');check('Workspace round trip keeps manual language; automatic detection can be restored');
 await open(p,'encoded.pde',encodeText('void setup() { size(100, 100); }\r\n// café 🛠️\n','utf-16be',true));await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();const promise=p.waitForEvent('download');await command(p,'Export workspace documents as ZIP');const zip=await promise;const entries=unzipSync(fs.readFileSync(await zip.path()));assert.deepEqual(entries['encoded.pde'],encodeText('void setup() { size(100, 100); }\r\n// café 🛠️\n','utf-16be',true));await context.setOffline(false);check('ZIP worker works after offline reload and preserves UTF-16BE BOM bytes');
 await open(p,'Case.txt','first');await open(p,'case.txt','second');await command(p,'Export workspace documents as ZIP');await p.waitForFunction(()=>document.getElementById('bannerText').textContent.includes('Paths conflict'));assert.equal((await download(p)).bytes.toString(),'second');await p.locator('#dismissBanner').click();check('Ambiguous ZIP paths fail with actionable feedback and leave documents intact');
 // An editing operation in a large file, not only an import/download benchmark.
 const large='bench line\n'.repeat(Math.ceil(5*1024*1024/11));await open(p,'large-edit.txt',large);const start=Date.now();await p.locator('.cm-content').press('Control+End');await p.keyboard.type('tail café');assert((await download(p)).bytes.toString().endsWith('tail café'));await p.locator('#undo').click();assert.equal((await download(p)).bytes.toString(),large);report.largeEdit={bytes:Buffer.byteLength(large),editDownloadUndoMs:Date.now()-start};check('5 MiB document edit, exact download, and undo');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/qualification-failure.png'});process.exitCode=1;}finally{await finish();}
