import {chromium as pw} from 'playwright';import chromium from '@sparticuz/chromium';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.cwd();const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://localhost').pathname.replace(/^\/typebench\//,'/');if(p.endsWith('/'))p+='index.html';const full=path.resolve(root,'.'+p);if(!full.startsWith(root+'/')){res.writeHead(403);res.end();return;}fs.readFile(full,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(full)]||'text/plain'});res.end(e?'':b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await pw.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||await chromium.executablePath(),args:chromium.args.filter(x=>!['--single-process','--disable-web-security','--allow-running-insecure-content','--disable-site-isolation-trials'].includes(x))});const ctx=await browser.newContext({viewport:{width:1440,height:960}});const p=await ctx.newPage();p.on('dialog',d=>d.accept());const checks=[];
try{
  await p.goto(`http://127.0.0.1:${server.address().port}/`);await p.locator('#emptyNew').click();await p.locator('.cm-content').fill('A fresh file');assert.equal(await p.locator('#fileStatus').textContent(),'No file copy yet');await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');checks.push('Root route and truthful new-file status');
  await p.locator('#sidebarDivider').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#sidebarDivider').getAttribute('aria-valuenow'),'230');await p.waitForFunction(()=>document.getElementById('browserStatus').textContent.includes('Saved in this browser'));await p.reload();assert.equal(await p.locator('#sidebarDivider').getAttribute('aria-valuenow'),'230');checks.push('Keyboard panel resize persisted after refresh');
  await p.locator('#filePicker').setInputFiles(Array.from({length:12},(_,i)=>({name:'long-filename-'+i+'.txt',mimeType:'text/plain',buffer:Buffer.from('Text '+i)})));await p.waitForFunction(()=>document.getElementById('filePath').textContent==='long-filename-11.txt');await p.setViewportSize({width:390,height:844});await p.waitForTimeout(150);const bounds=await p.locator('#tabs [aria-selected=true]').boundingBox();assert(bounds.x>=-1 && bounds.x+bounds.width<=391);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(await p.locator('#sidebarToggle').getAttribute('aria-expanded')==='true')await p.locator('#sidebarToggle').click();await p.locator('.cm-content').focus();await p.screenshot({path:'docs/screenshots/mobile.png'});checks.push('Active tab remains visible after mobile resize and focus is visible');
  const count=await p.locator('[role=tab]').count();await p.locator('#workspacePicker').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await p.waitForFunction(()=>document.getElementById('bannerText').textContent.includes('Workspace import failed'));assert.equal(await p.locator('[role=tab]').count(),count);assert.equal(await p.locator('.cm-content').innerText(),'Text 11');checks.push('Malformed workspace leaves current documents intact');
  const result={version:JSON.parse(fs.readFileSync('package.json')).version,success:true,checks};fs.writeFileSync('docs/release-checks.json',JSON.stringify(result,null,2));console.log(result);
}finally{await browser.close();server.close();}
