import assert from 'node:assert/strict';
import {harness,waitSaved,open,download,command} from './harness.mjs';
const {p,url,context,report,check,finish}=await harness('snippet-boundaries');
async function create(){await p.locator('.cm-content').press('Control+a');await p.locator('#snippetCreate').click();await p.waitForFunction(()=>!document.getElementById('snippetPNG').disabled);}
try{
 await p.goto(url);await waitSaved(p);const long='const longLine = "'+'x'.repeat(30000)+'";';await open(p,'wide.js',long);await create();await p.locator('#snippetPNG').click();await p.waitForFunction(()=>document.getElementById('snippetStatus').textContent.includes('too large'));assert((await download(p,'#snippetSVG')).bytes.toString().includes('x'.repeat(30000)));assert((await download(p,'#snippetHTML')).bytes.toString().includes('x'.repeat(30000)));await p.locator('#snippetDialog [data-close]').click();assert.equal((await download(p)).bytes.toString(),long);check('A 30,000-character line refuses oversized PNG allocation but exports full SVG/HTML and keeps source intact');
 await p.evaluate(()=>{window.RealWorker=window.Worker;window.Worker=function(url,...args){if(String(url).includes('snippet-worker'))return {postMessage(){},terminate(){}};return new RealWorker(url,...args);};});await open(p,'small.ino','void setup() { pinMode(13, OUTPUT); }');await create();assert((await p.locator('#snippetStatus').textContent()).includes('took too long'));assert(await p.locator('#snippetRetry').isVisible());assert((await download(p,'#snippetSVG')).bytes.toString().includes('pinMode'));await p.evaluate(()=>window.Worker=window.RealWorker);await p.locator('#snippetRetry').click();await p.waitForFunction(()=>document.getElementById('snippetStatus').textContent.startsWith('Ready to export'));await p.locator('#snippetSave').click();await p.locator('#snippetDialog [data-close]').click();check('Slow syntax worker falls back to plain exports; retry restores colors');
 const backup=JSON.parse((await download(p,'#backup')).bytes);const bad=structuredClone(backup);bad.snippets[0].spans=[[0,1,'<script>']];await p.locator('#workspacePicker').setInputFiles({name:'invalid-snippets.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.waitForFunction(()=>document.getElementById('bannerText').textContent.includes('Workspace import failed'));assert.equal(await p.locator('#snippetCount').textContent(),'1');assert.equal((await download(p)).bytes.toString(),'void setup() { pinMode(13, OUTPUT); }');await p.locator('#dismissBanner').click();check('Malformed imported snippet data is rejected before replacing existing documents or snippets');
 await waitSaved(p);const second=await context.newPage();second.on('dialog',d=>d.accept());await second.goto(url);await waitSaved(second);await p.locator('.cm-content').press('Control+End');await p.keyboard.type(' // first window');await waitSaved(p);
 await second.locator('.cm-content').press('Control+a');await second.locator('#snippetCreate').click();await second.waitForFunction(()=>!document.getElementById('snippetPNG').disabled);await second.locator('#snippetSave').click();await second.waitForFunction(()=>document.getElementById('snippetBrowserStatus').textContent.includes('Conflict'));await second.locator('#snippetDialog [data-close]').click();const recovery=JSON.parse((await download(second,'#emergencyExport')).bytes);assert.equal(recovery.snippets.length,2);await second.close();await p.reload();await waitSaved(p);assert.equal(await p.locator('#snippetCount').textContent(),'1');assert((await download(p)).bytes.toString().endsWith('// first window'));check('Conflicting app windows cannot overwrite snippets or documents; the blocked copy is exportable');
 await command(p,'Fresh Start');await p.locator('#confirmYes').click();await waitSaved(p);await p.reload();assert.equal(await p.locator('#snippetCount').textContent(),'0');assert.equal(await p.locator('#documentCount').textContent(),'0');check('Fresh Start clears saved snippets and documents durably after confirmation');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);process.exitCode=1;}finally{await finish();}
