import assert from 'node:assert/strict';
import fs from 'node:fs';
import AxeBuilder from '@axe-core/playwright';
import {harness,waitSaved,open,download,command} from './harness.mjs';
const {p,url,context,report,check,finish}=await harness('snippets');
const selected='  size(640, 400);\r\n  // café 🛠️ 日本語\n  PVector p = new PVector(10, 20);\r\n  println("<script>bad()</script>");';
const original='// PRIVATE before selection\r\nvoid setup() {\r\n'+selected+'\r\n}\n// PRIVATE after selection';
async function ready(){await p.waitForFunction(()=>!document.getElementById('snippetPNG').disabled);}
async function audit(name){const a=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();if(a.violations.length)console.log(JSON.stringify(a.violations,null,2));assert.deepEqual(a.violations.map(x=>x.id),[],name);}
try{
 await p.goto(url);await waitSaved(p);await open(p,'sketch.pde',original);assert(await p.locator('#snippetCreate').isDisabled());
 await p.keyboard.press('Control+g');await p.locator('#gotoInput').fill('3:1');await p.locator('#gotoForm [type=submit]').click();await p.keyboard.down('Shift');await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowDown');await p.keyboard.press('End');await p.keyboard.up('Shift');
 await p.locator('#snippetCreate').click();await ready();assert.equal(await p.locator('#snippetStartLine').inputValue(),'3');assert((await p.locator('#snippetPreview code').textContent()).includes('PVector'));assert(!(await p.locator('#snippetPreview code').textContent()).includes('PRIVATE'));check('Selected Processing code creates a snippet without surrounding text');
 await p.locator('#snippetName').fill('Orbit setup');const svg=(await download(p,'#snippetSVG')).bytes.toString();assert(svg.includes('fill="#8bd9ea"'));assert(svg.includes('&lt;script&gt;'));assert(!svg.includes('<script>'));assert(!svg.includes('PRIVATE'));fs.writeFileSync('docs/snippet-sample.svg',svg);
 const png=await download(p,'#snippetPNG');assert.deepEqual([...png.bytes.subarray(0,8)],[137,80,78,71,13,10,26,10]);assert(png.bytes.readUInt32BE(16)>300);fs.writeFileSync('docs/snippet-sample.png',png.bytes);await p.locator('#snippetScale').selectOption('1');const oneX=await download(p,'#snippetPNG');assert.equal(oneX.bytes.readUInt32BE(16)*2,png.bytes.readUInt32BE(16));await p.locator('#snippetFontSize').selectOption('24');assert((await download(p,'#snippetPNG')).bytes.readUInt32BE(16)>oneX.bytes.readUInt32BE(16));await p.locator('#snippetFontSize').selectOption('16');await p.locator('#snippetScale').selectOption('2');check('Processing colors, Unicode source, font size, PNG scale, and safe SVG/PNG exports');
 const html=(await download(p,'#snippetHTML')).bytes.toString();assert(html.includes("default-src 'none'"));assert(html.includes('&lt;script&gt;'));assert(!html.includes('PRIVATE'));assert(!/<script|<iframe|<img/.test(html));
 await context.grantPermissions(['clipboard-read','clipboard-write']);await p.locator('#snippetCopyHTML').click();await p.waitForFunction(()=>document.getElementById('snippetStatus').textContent==='HTML embed copied.');const embed=await p.evaluate(()=>navigator.clipboard.readText());assert(embed.startsWith('<figure'));assert(embed.includes('color:#8bd9ea'));
 await p.locator('#snippetCopyMarkdown').click();await p.waitForFunction(()=>document.getElementById('snippetStatus').textContent==='Markdown copied.');const md=await p.evaluate(()=>navigator.clipboard.readText());assert(md.startsWith('```processing\r\n'));assert(md.includes(selected));
 await p.locator('#snippetCopyCode').click();await p.waitForFunction(()=>document.getElementById('snippetStatus').textContent==='Code copied.');assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),selected);check('HTML, Markdown, and exact-source copy preserve safe selected content');
 await p.evaluate(()=>{window.realWriteText=navigator.clipboard.writeText.bind(navigator.clipboard);navigator.clipboard.writeText=()=>Promise.reject(new DOMException('Test denial','NotAllowedError'));});await p.locator('#snippetCopyHTML').click();assert(await p.locator('#snippetCopyDialog').isVisible());assert.equal(await p.locator('#snippetCopyText').inputValue(),embed);const fallback=(await download(p,'#snippetCopyDownload')).bytes.toString();assert.equal(fallback,embed);await p.locator('#snippetCopyDialog [data-close]').click();await p.evaluate(()=>navigator.clipboard.writeText=window.realWriteText);check('Denied clipboard permission offers selectable output and download fallback');
 for(const theme of ['dark','light','contrast']){await p.locator('#snippetDialog [data-close]').click();await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption(theme);await p.locator('#settingsDialog [data-close]').click();await p.locator('#snippetCreate').click();await ready();await p.locator('#snippetName').fill('Orbit setup');await audit(theme+' snippet preview and interface');await p.screenshot({path:'docs/screenshots/snippet-'+theme+'.png'});}await p.locator('#snippetDialog [data-close]').click();await p.locator('#settingsOpen').click();await p.locator('#theme').selectOption('dark');await p.locator('#settingsDialog [data-close]').click();await p.locator('#snippetCreate').click();await ready();await p.locator('#snippetName').fill('Orbit setup');
 await p.locator('#snippetTheme').selectOption('dark');await p.locator('#snippetTransparent').check();const transparent=(await download(p,'#snippetPNG')).bytes;fs.writeFileSync('docs/snippet-transparent.png',transparent);const pixel=await p.evaluate(async b=>{const img=await createImageBitmap(new Blob([Uint8Array.from(atob(b),c=>c.charCodeAt(0))],{type:'image/png'}));const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d').drawImage(img,0,0);const alpha=c.getContext('2d').getImageData(0,0,1,1).data[3];img.close();return alpha;},transparent.toString('base64'));assert.equal(pixel,0);await p.locator('#snippetTransparent').uncheck();await p.locator('#snippetShowFilename').uncheck();await p.locator('#snippetLineNumbers').uncheck();assert.equal(await p.locator('#snippetPreview figcaption').count(),0);await p.locator('#snippetShowFilename').check();await p.locator('#snippetLineNumbers').check();await p.locator('#snippetSave').click();await waitSaved(p);await p.locator('#snippetDialog [data-close]').click();assert.equal((await download(p)).bytes.toString(),original);check('Three themes, transparency, optional labels/numbers, and source preservation');
 const backup=(await download(p,'#backup')).bytes;const data=JSON.parse(backup);assert.equal(data.snippets.length,1);assert.equal(data.snippets[0].raw,selected);assert(!JSON.stringify(data.snippets).includes('PRIVATE'));await p.reload();await waitSaved(p);await p.locator('#snippetsOpen').click();assert.equal(await p.locator('.saved-snippet').count(),1);await p.locator('.saved-snippet button').filter({hasText:'Preview / export'}).click();assert(await p.locator('#snippetSave').isDisabled());assert.equal(await p.locator('#snippetName').inputValue(),'Orbit setup');await p.locator('#snippetName').fill('Updated orbit');await p.locator('#snippetSave').click();await p.locator('#snippetSaveCopy').click();await p.locator('#snippetDialog [data-close]').click();assert.equal(await p.locator('#snippetCount').textContent(),'2');check('Reusable snippets survive refresh; edits and save-a-copy stay distinct');
 await p.locator('#workspacePicker').setInputFiles({name:'workspace.json',mimeType:'application/json',buffer:backup});await p.locator('#confirmYes').click();await p.waitForFunction(()=>document.getElementById('snippetCount').textContent==='1');await p.locator('#new').click();await p.locator('.cm-content').fill('before\n');await p.locator('.cm-content').press('Control+End');await command(p,'Saved snippets');await p.locator('.saved-snippet button').filter({hasText:/^Insert$/}).click();assert.equal((await download(p)).bytes.toString(),'before\n'+selected.replace(/\r\n/g,'\n'));await p.locator('#undo').click();assert.equal((await download(p)).bytes.toString(),'before\n');await p.locator('#redo').click();assert((await download(p)).bytes.toString().includes('PVector'));check('Workspace JSON restores snippets; insertion uses one undo/redo step');
 await command(p,'Saved snippets');await p.locator('.saved-snippet button').filter({hasText:'Open as document'}).click();assert.equal((await download(p)).bytes.toString(),selected);assert.equal(await p.locator('#language').inputValue(),'processing');check('Opening a snippet as a document retains original line endings and language');
 await p.waitForFunction(()=>document.getElementById('offline').textContent==='Offline ready');await waitSaved(p);await context.setOffline(true);await p.reload();await p.locator('.cm-content').press('Control+a');await command(p,'Create snippet from selection');await ready();assert((await download(p,'#snippetSVG')).bytes.toString().includes('PVector'));assert((await download(p,'#snippetPNG')).bytes.length>1000);await p.locator('#snippetDialog [data-close]').click();await context.setOffline(false);check('Snippet parsing, PNG, and SVG work after offline reload at a subdirectory');
 await open(p,'inside-comment.ino','/* hidden prefix\ncomment inside a block\nend */\nvoid setup() {}');await p.locator('.cm-content').press('Control+Home');await p.keyboard.press('ArrowDown');await p.keyboard.press('Home');await p.keyboard.press('Shift+End');await p.locator('#snippetCreate').click();await ready();const comment=(await download(p,'#snippetSVG')).bytes.toString();assert(comment.includes('fill="#93aa9b"'));assert(!comment.includes('hidden prefix'));await p.locator('#snippetDialog [data-close]').click();check('Partial multiline constructs use document syntax context without exporting it');
 await open(p,'blink.ino','void setup() { pinMode(LED_BUILTIN, OUTPUT); }\nvoid loop() { digitalWrite(LED_BUILTIN, HIGH); delay(500); }');await p.locator('.cm-content').press('Control+a');await p.locator('#snippetCreate').click();await ready();const arduino=(await download(p,'#snippetSVG')).bytes.toString();assert(arduino.includes('fill="#8bd9ea"'));assert(arduino.includes('>digitalWrite</tspan>'));assert(arduino.includes('>HIGH</tspan>'));check('Arduino snippet exports recognize standard functions and constants');
 await p.setViewportSize({width:320,height:740});await audit('Mobile snippet dialog');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'docs/screenshots/snippet-mobile-320.png'});await p.locator('#snippetDialog [data-close]').click();await p.setViewportSize({width:1440,height:1000});check('Snippet UI remains accessible at 320 pixels with no page overflow');
 await p.evaluate(()=>{window.originalTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(n,m,...r){if(m==='readwrite')throw new DOMException('Simulated full storage','QuotaExceededError');return originalTransaction.call(this,n,m,...r);};});await p.locator('.cm-content').press('Control+a');await p.locator('#snippetCreate').click();await ready();await p.locator('#snippetSave').click();await p.locator('#snippetDialog [data-close]').click();await p.waitForFunction(()=>!document.getElementById('retryStorage').hidden);assert(JSON.parse((await download(p,'#emergencyExport')).bytes).snippets.some(s=>s.language==='arduino'));await p.evaluate(()=>IDBDatabase.prototype.transaction=originalTransaction);await p.locator('#retryStorage').click();await waitSaved(p);check('Storage failure recovery export includes new snippets and retry saves them');
 await command(p,'Saved snippets');await p.locator('#snippetSearch').fill('Orbit');assert.equal(await p.locator('.saved-snippet').count(),1);await p.locator('.saved-snippet button').filter({hasText:/^Delete$/}).click();await p.locator('#confirmDialog button[value=cancel]').last().click();assert.equal(await p.locator('.saved-snippet').count(),1);await p.locator('.saved-snippet button').filter({hasText:/^Delete$/}).click();await p.locator('#confirmYes').click();await p.locator('.saved-snippet').waitFor({state:'detached'});assert.equal(await p.locator('.saved-snippet').count(),0);await p.locator('#snippetsDialog [data-close]').click();check('Saved snippet search and confirmed deletion work without changing documents');
 assert.deepEqual(report.errors,[]);report.success=true;
}catch(e){report.success=false;report.failure=e.stack;console.error(e);await p.screenshot({path:'docs/screenshots/snippets-failure.png'});process.exitCode=1;}finally{await finish();}
